language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
  
before_script:
  - uname -a
  - ./travis.sh createdb ragnarok root
  - ./travis.sh importdb ragnarok travis
  - mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis');"

script:
  - ./travis.sh build $CONFIGURE_FLAGS
  - ./travis.sh test ragnarok travis travis

# We can't use this, unfortunately
# http://github.com/travis-ci/travis-ci/issues/979
#compiler:
#  - clang
#  - gcc

matrix:
  exclude:
  - env: ignore=this
  include:
  - compiler: clang
    env: CONFIGURE_FLAGS="--enable-debug=yes --enable-64bit"
  - compiler: clang
    env: CONFIGURE_FLAGS="--enable-64bit"
  - compiler: gcc
    env: CONFIGURE_FLAGS="--enable-64bit --enable-debug=yes"
  - compiler: gcc
    env: CONFIGURE_FLAGS="--enable-64bit"
  
notifications:
  email: false

